# Generated by Django 4.0.4 on 2022-06-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tags',
            field=models.CharField(default='SanBlog', max_length=255),
        ),
    ]
