# Generated by Django 4.0.4 on 2022-06-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sblog', '0002_post_title_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title_tags',
            new_name='title_tag',
        ),
    ]
